const data = [
    {
        id: '1', 
        movie: 'Зелёная миля/The Green Mile',
        image: 'img/green_mile.jpg',
        year: 1999,
        country: 'USA',
        director: 'Фрэнк Дарабонт',
        actors: 'Том Хэнкс, Дэвид Морс, Майкл Кларк Дункан',
        plot: 'Стивен Кинг',
        trailer: 'link',
        facts: 'Факты'
    },
    {
        id: '2', 
        movie: 'Побе́г из Шоуше́нка/The Shawshank Redemption',
        image: 'img/shawshank_redemption.jpg',
        year: 1994,
        country: 'USA',
        director: 'Фрэнк Дарабонт',
        actors: 'Тим Роббинс, Морган Фриман, Боб Гантон',
        plot: 'Фрэнк Дарабонт',
        trailer: 'link',
        facts: 'Факты'
    },
    {
        id: '3', 
        movie: 'Властели́н коле́ц: Возвраще́ние короля́/The Lord of the Rings: The Return of the King',
        image: 'img/lord_of_the_rings_the_return_of_the_king.jpg',
        year: 2003,
        country: 'USA',
        director: 'Питер Джексон',
        actors: 'Элайджа Вуд, Вигго Мортенсен, Шон Астин',
        plot: 'Дж. Р. Р. Толкин',
        trailer: 'link',
        facts: 'Факты'
    },
    {
        id: '4', 
        movie: 'Властели́н коле́ц: Две кре́пости/The Lord of the Rings: The Two Towers',
        image: 'img/lord_of_the_rings_two_towers.jpg',
        year: 2002,
        country: 'USA',
        director: 'Питер Джексон',
        actors: 'Элайджа Вуд, Вигго Мортенсен, Шон Астин',
        plot: 'Дж. Р. Р. Толкин',
        trailer: 'link',
        facts: 'Факты'
    },
    {
        id: '5', 
        movie: 'Властели́н коле́ц: Бра́тство Кольца́/The Lord of the Rings: The Fellowship of the Ring',
        image: 'img/lord_of_the_rings_fellowship.jpg',
        year: 2001,
        country: 'USA',
        director: 'Питер Джексон',
        actors: 'Элайджа Вуд, Иэн Маккеллен, Вигго Мортенсен',
        plot: 'Дж. Р. Р. Толкин',
        trailer: 'link',
        facts: 'Факты'
    },
    {
        id: '6', 
        movie: 'Фо́ррест Гамп/Forrest Gump',
        image: 'img/forrest_gump.jpg',
        year: 1994,
        country: 'USA',
        director: 'Роберт Земекис',
        actors: 'Том Хэнкс, Робин Райт, Гэри Синиз',
        plot: 'Эрик Рот',
        trailer: 'link',
        facts: 'Факты'
    },  
    {
        id: '7', 
        movie: 'Король Лев/The Lion King',
        image: 'img/lion_king.jpg',
        year: 1994,
        country: 'USA',
        director: 'Роджер Аллерс',
        actors: '-',
        plot: 'Линда Вулвертон',
        trailer: 'link',
        facts: 'Факты'
    },
    {
        id: '8', 
        movie: 'Карты, деньги, два ствола/Lock, Stock and Two Smoking Barrels',
        image: 'img/lock_stock_and_two_smoking.jpg',
        year: 1998,
        country: 'Great Britain',
        director: 'Гай Ричи',
        actors: 'Ник Моран, Джейсон Флеминг, Декстер Флетчер',
        plot: 'Гай Ричи',
        trailer: 'link',
        facts: 'Факты'
    },
    {
        id: '9', 
        movie: 'ВАЛЛ-И/WALL-E',
        image: 'img/WALL-E.png',
        year: 2008,
        country: 'USA',
        director: 'Эндрю Стэнтон',
        actors: '-',
        plot: 'Эндрю Стэнтон',
        trailer: 'link',
        facts: 'Факты'
    },  
    {
        id: '10', 
        movie: 'Спи́сок Ши́ндлера/Schindlers List',
        image: 'img/schindlers_list.jpg',
        year: 1993,
        country: 'USA',
        director: 'Стивен Спилберг',
        actors: 'Лиам Нисон, Бен Кингсли, Рэйф Файнс',
        plot: 'Стивен Заиллян',
        trailer: 'link',
        facts: 'Факты'
    },
    {
        id: '11', 
        movie: 'Большой куш/Snatch',
        image: 'img/snatch.jpg',
        year: 2000,
        country: 'Great Britain',
        director: 'Гай Ричи',
        actors: 'Джейсон Стейтем, Бенисио дель Торо, Стивен Грэм',
        plot: 'Гай Ричи',
        trailer: 'link',
        facts: 'Факты'
    },
    {
        id: '12', 
        movie: 'Кримина́льное чти́во/Pulp Fiction',
        image: 'img/pulp_fiction.jpg',
        year: 1994,
        country: 'USA',
        director: 'Квентин Тарантино',
        actors: 'Джон Траволта, Сэмюэл Л. Джексон, Брюс Уиллис',
        plot: 'Квентин Тарантино',
        trailer: 'link',
        facts: 'Факты'
    },  
    {
        id: '13', 
        movie: 'Назад в будущее/Back to the Future',
        image: 'img/bttf.jpg',
        year: 1985,
        country: 'USA',
        director: 'Роберт Земекис',
        actors: 'Майкл Джей Фокс, Кристофер Ллойд, Криспин Гловер',
        plot: 'Роберт Земекис',
        trailer: 'link',
        facts: 'Факты'
    },
    {
        id: '14', 
        movie: '1+1/Intouchables',
        image: 'img/intouchables.jpg',
        year: 2011,
        country: 'France',
        director: 'Оливье Накаш',
        actors: 'Франсуа Клюзе, Омар Си',
        plot: 'Оливье Накаш',
        trailer: 'link',
        facts: 'Факты'
    },
    {
        id: '15', 
        movie: 'Пираты Карибского моря: Проклятие Чёрной жемчужины/Pirates of the Caribbean: The Curse of The Black Pearl',
        image: 'img/pirates_of_the_caribbean.jpg',
        year: 2003,
        country: 'USA',
        director: 'Гор Вербински',
        actors: 'Джонни Депп, Орландо Блум, Кира Найтли',
        plot: 'Тед Эллиот',
        trailer: 'link',
        facts: 'Факты'
    },  
    {
        id: '16', 
        movie: 'Матрица/The Matrix',
        image: 'img/matrix.jpg',
        year: 1999,
        country: 'USA',
        director: 'братья Вачовски',
        actors: 'Киану Ривз, Лоуренс Фишборн, Керри-Энн Мосс',
        plot: 'братья Вачовски',
        trailer: 'link',
        facts: 'Факты'
    },
    {
        id: '17', 
        movie: 'Остров проклятых/Shutter Island',
        image: 'img/shutter_island.jpg',
        year: 2010,
        country: 'USA',
        director: 'Мартин Скорсезе',
        actors: 'Леонардо Ди Каприо, Марк Руффало, Бен Кингсли',
        plot: 'Лаэта Калогридис',
        trailer: 'link',
        facts: 'Факты'
    },
    {
        id: '18', 
        movie: 'Достуча́ться до небе́с/Knockin On Heavens Door',
        image: 'img/knockin_on_heavens_door.jpg',
        year: 1997,
        country: 'Germany',
        director: 'Томас Ян',
        actors: 'Тиль Швайгер, Ян Йозеф Лиферс, Мориц Блайбтрой',
        plot: 'Томас Ян',
        trailer: 'link',
        facts: 'Факты'
    },  
    {
        id: '19', 
        movie: 'Джентльмены/The Gentlemen',
        image: 'img/gentlemen.jpg',
        year: 2019,
        country: 'Great Britain',
        director: 'Гай Ричи',
        actors: 'Чарли Ханнэм, Генри Голдинг, Мишель Докери',
        plot: 'Гай Ричи',
        trailer: 'link',
        facts: 'Факты'
    },
    {
        id: '20', 
        movie: 'Бойцо́вский клуб/Fight Club',
        image: 'img/fight_club.jpg',
        year: 1999,
        country: 'USA',
        director: 'Дэвид Финчер',
        actors: 'Эдвард Нортон, Брэд Питт, Хелена Бонэм Картер',
        plot: 'Чак Паланик',
        trailer: 'link',
        facts: 'Факты'
    },
    {
        id: '21', 
        movie: 'Шрек/Shrek',
        image: 'img/shrek.jpg',
        year: 2001,
        country: 'USA',
        director: 'Эндрю Адамсон',
        actors: '-',
        plot: 'Тед Эллиот',
        trailer: 'link',
        facts: 'Факты'
    },
    {
        id: '22', 
        movie: 'Душа́/Soul',
        image: 'img/soul.jpg',
        year: 2020,
        country: 'USA',
        director: 'Пит Доктер',
        actors: '-',
        plot: 'Пит Доктер',
        trailer: 'link',
        facts: 'Факты'
    },    
    {
        id: '23', 
        movie: 'Невидимая сторона/The Blind Side',
        image: 'img/blind_side.jpg',
        year: 2009,
        country: 'USA',
        director: 'Джон Ли Хэнкок',
        actors: 'Сандра Буллок, Тим Макгро, Куинтон Аарон',
        plot: 'Майкл Льюис',
        trailer: 'link',
        facts: 'Факты'
    },    
    {
        id: '24', 
        movie: 'Прести́ж/The Prestige',
        image: 'img/prestige.jpg',
        year: 2006,
        country: 'USA',
        director: 'Кристофер Нолан',
        actors: 'Хью Джекман, Кристиан Бейл, Скарлетт Йоханссон',
        plot: 'Кристофер Прист',
        trailer: 'link',
        facts: 'Факты'
    },    
    {
        id: '25', 
        movie: 'Один дома/Home Alone',
        image: 'img/home_alone.jpg',
        year: 1990,
        country: 'USA',
        director: 'Крис Коламбус',
        actors: 'Маколей Калкин, Джо Пеши, Дэниел Стерн',
        plot: 'Джон Хьюз',
        trailer: 'link',
        facts: 'Факты'
    },    
    {
        id: '26', 
        movie: 'Тёмный рыцарь/The Dark Knight',
        image: 'img/dark_knigth.jpg',
        year: 2008,
        country: 'USA',
        director: 'Кристофер Нолан',
        actors: 'Кристиан Бейл, Хит Леджер, Гэри Олдмен',
        plot: 'Кристофер Нолан',
        trailer: 'link',
        facts: 'Факты'
    },    
    {
        id: '27', 
        movie: 'Термина́тор 2: Су́дный день/Terminator 2: Judgment Day',
        image: 'img/terminator2.jpg',
        year: 1991,
        country: 'USA',
        director: 'Джеймс Кэмерон',
        actors: 'Арнольд Шварценеггер, Линда Хэмилтон, Эдвард Фёрлонг',
        plot: 'Джеймс Кэмерон',
        trailer: 'link',
        facts: 'Факты'
    },    
    {
        id: '28', 
        movie: 'Назад в будущее 2/Back To The Future, Part II',
        image: 'img/back_to_future_part_2.jpg',
        year: 1989,
        country: 'USA',
        director: 'Роберт Земекис',
        actors: 'Майкл Джей Фокс, Кристофер Ллойд, Томас Ф. Уилсон',
        plot: 'Боб Гейл',
        trailer: 'link',
        facts: 'Факты'
    },    
    {
        id: '29', 
        movie: 'Га́рри По́ттер и у́зник Азкаба́на/Harry Potter and the Prisoner of Azkaban',
        image: 'img/harry_potter_and_the_prisoner_of_azkaban.jpg',
        year: 2004,
        country: 'Great Britain',
        director: 'Альфонсо Куарон',
        actors: 'Дэниел Рэдклифф, Руперт Гринт, Эмма Уотсон',
        plot: 'Стив Кловис',
        trailer: 'link',
        facts: 'Факты'
    },    
    {
        id: '30', 
        movie: 'Одержимость/Whiplash',
        image: 'img/whiplash.jpg',
        year: 2014,
        country: 'USA',
        director: 'Дэмьен Шазелл',
        actors: 'Майлз Теллер, Дж. К. Симмонс',
        plot: 'Дэмьен Шазелл',
        trailer: 'link',
        facts: 'Факты'
    },    
    {
        id: '31', 
        movie: 'Твоё имя/Your Name',
        image: 'img/kimi_no_na_wa.jpg',
        year: 2016,
        country: 'Japan',
        director: 'Макото Синкай',
        actors: '-',
        plot: 'Макото Синкай',
        trailer: 'link',
        facts: 'Факты'
    },       
    {
        id: '32', 
        movie: 'Лео́н/Léon',
        image: 'img/leon.jpg',
        year: 1994,
        country: 'France',
        director: 'Люк Бессон',
        actors: 'Жан Рено, Натали Портман, Гэри Олдмен',
        plot: 'Люк Бессон',
        trailer: 'link',
        facts: 'Факты'
    },        
    {
        id: '33', 
        movie: 'Гарри Поттер и философский камень/Harry Potter and the Philosopher’s Stone',
        image: 'img/harry_potter_and_the_philosophers_stone.jpg',
        year: 2001,
        country: 'Great Britain',
        director: 'Крис Коламбус',
        actors: 'Дэниел Рэдклифф, Руперт Гринт, Эмма Уотсон',
        plot: 'Стив Кловис',
        trailer: 'link',
        facts: 'Факты'
    },        
    {
        id: '34', 
        movie: 'Джанго освобождённый/Django Unchained',
        image: 'img/django_unchained.jpg',
        year: 2012,
        country: 'USA',
        director: 'Квентин Тарантино',
        actors: 'Джейми Фокс, Кристоф Вальц, Леонардо Ди Каприо',
        plot: 'Квентин Тарантино',
        trailer: 'link',
        facts: 'Факты'
    },        
    {
        id: '35', 
        movie: 'Гладиа́тор/Gladiator',
        image: 'img/gladiator.jpg',
        year: 2000,
        country: 'USA',
        director: 'Ридли Скотт',
        actors: 'Рассел Кроу, Хоакин Феникс, Конни Нилсен',
        plot: 'Джон Логан',
        trailer: 'link',
        facts: 'Факты'
    },        
    {
        id: '36', 
        movie: 'Отступники/The Departed',
        image: 'img/departed.jpg',
        year: 2006,
        country: 'USA',
        director: 'Мартин Скорсезе',
        actors: 'Леонардо Ди Каприо, Мэтт Деймон, Джек Николсон',
        plot: 'Уильям Монахан',
        trailer: 'link',
        facts: 'Факты'
    },        
    {
        id: '37', 
        movie: 'Зелёная книга/Green Book',
        image: 'img/green_book.jpg',
        year: 2018,
        country: 'USA',
        director: 'Питер Фаррелли',
        actors: 'Вигго Мортенсен, Махершала Али',
        plot: 'Ник Валлелонга',
        trailer: 'link',
        facts: 'Факты'
    },        
    {
        id: '38', 
        movie: 'Молча́ние ягня́т/The Silence of the Lambs',
        image: 'img/the_silence_of_the_lambs.jpg',
        year: 1991,
        country: 'USA',
        director: 'Джонатан Демми',
        actors: 'Энтони Хопкинс, Джоди Фостер, Скотт Гленн',
        plot: 'Томас Харрис',
        trailer: 'link',
        facts: 'Факты'
    },        
    {
        id: '39', 
        movie: 'Волк с Уолл-стрит/The Wolf of Wall Street',
        image: 'img/the_wolf_of_wall_street.jpg',
        year: 2013,
        country: 'USA',
        director: 'Мартин Скорсезе',
        actors: 'Леонардо Ди Каприо, Джона Хилл, Марго Робби',
        plot: 'Теренс Уинтер',
        trailer: 'link',
        facts: 'Факты'
    },   
    {
        id: '40', 
        movie: 'Корпора́ция мо́нстров/Monsters, Inc',
        image: 'img/monsters.jpg',
        year: 2001,
        country: 'USA',
        director: 'Пит Доктер',
        actors: '-',
        plot: 'Пит Доктер',
        trailer: 'link',
        facts: 'Факты'
    },    
    {
        id: '41', 
        movie: 'Ратату́й/Ratatouille',
        image: 'img/ratatui.jpg',
        year: 2007,
        country: 'USA',
        director: 'Брэд Бёрд',
        actors: '-',
        plot: 'Брэд Бёрд',
        trailer: 'link',
        facts: 'Факты'
    },    
    {
        id: '42', 
        movie: 'Пойма́й меня́, е́сли смо́жешь/Catch Me If You Can',
        image: 'img/catch_me_if_you_can.jpg',
        year: 2002,
        country: 'USA',
        director: 'Стивен Спилберг',
        actors: 'Леонардо Ди Каприо, Том Хэнкс, Кристофер Уокен',
        plot: 'Фрэнк У. Абигнейл мл.',
        trailer: 'link',
        facts: 'Факты'
    },    
    {
        id: '43', 
        movie: 'Укрощение строптивого/Il bisbetico domato',
        image: 'img/il_bisbetico_domato.jpg',
        year: 1980,
        country: 'Italy',
        director: 'Кастеллано и Пиполо',
        actors: 'Адриано Челентано, Орнелла Мути',
        plot: 'Кастеллано и Пиполо',
        trailer: 'link',
        facts: 'Факты'
    },    
    {
        id: '44', 
        movie: 'Стальной гигант/The Iron Giant',
        image: 'img/iron_giant.jpg',
        year: 1999,
        country: 'USA',
        director: 'Брэд Бёрд',
        actors: '-',
        plot: 'Тим МакКэнлис',
        trailer: 'link',
        facts: 'Факты'
    },     
    {
        id: '45', 
        movie: 'Тита́ник/Titanic',
        image: 'img/titanic.png',
        year: 1997,
        country: 'USA',
        director: 'Джеймс Кэмерон',
        actors: 'Леонардо Ди Каприо, Кейт Уинслет, Билли Зейн',
        plot: 'Джеймс Кэмерон',
        trailer: 'link',
        facts: 'Факты'
    },         
];